### ISSUE TITLE
Mission Feedback

### ISSUE THREAD

**Issue by n0dane** [unitedoperations/uo-discordbot#19]
As a mission maker is one of the worst thing to hear when starting up a mission. "oh no not this mission its bad because of xyz..." yet as the mission maker, that is for the most part the first time you hear it.. No one uses the mission lists comment section... So how about we use it through the bot?

This is a suggestion to add a mission feedback button directly in discord.

1. add a button on the"NEW MISSION" message that is being posted in the "#chat-A3" channel. with the text "FEEDBACK".

2. When clicked should it do one of the following.
2.A Open up a chat message to the bot. Anything that is written is added as comment to the mission in the mission list: http://forums.unitedoperations.net/index.php/page/ArmA3/missionlist/_/livemissions/tvt45-run-the-gauntlet-v8-r805
2.B alternative just have it open up the mission.

**Comment by callensm** [comment]
Since there is no open API associated with forum pasted operations, there wouldn't be any way for me to create a comment based on a message from the bot unless I simulated the on-page actions via a headless browser like `puppeteer`.

I can implement it as a link on each that simply opens the feedback page for that mission though...(2.B)

**Comment by callensm** [comment]
Implemented in #20 
Will be pushed in version 2.4.0 release
